apiVersion: apps/v1
kind: Deployment
metadata:
  name: gdpr-anonymizer
spec:
  template:
    spec:
      containers:
      - name: gdpr-anonymizer
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 2000m
            memory: 2Gi
