llm:
  provider: "ollama"  # or "openai" or "ollama"
  model: "phi4:14b"
  temperature: 0.1
  max_tokens: 25000
  api_key_env: "sk-ollama-12345-secret"
  ollama:
    base_url: "https://ollama.lacambra.tech"
    auth_token: sk-ollama-12345-secret  # Optional: set if your Ollama instance requires authentication

agents:
  agent1:
    name: "ANON-EXEC"
    enabled: true
    prompt_version: "v1"

  agent2:
    name: "DIRECT-CHECK"
    enabled: true
    prompt_version: "v1"

  agent3:
    name: "RISK-ASSESS"
    enabled: true
    prompt_version: "v1"

orchestration:
  max_iterations: 3
  timeout_seconds: 300
