apiVersion: v1
kind: ConfigMap
metadata:
  name: gdpr-anonymizer-config
  labels:
    app: gdpr-anonymizer
data:
  config.yaml: |
    # LLM Provider Configuration
    llm_provider: "claude"  # claude, openai, or ollama

    claude:
      model: "claude-3-5-sonnet-20241022"
      max_tokens: 4096
      temperature: 0.0

    openai:
      model: "gpt-4"
      max_tokens: 4096
      temperature: 0.0

    ollama:
      model: "llama2"
      base_url: "http://localhost:11434"

    # Anonymization Settings
    anonymization:
      max_iterations: 3
      validation_threshold: 0.8
      risk_threshold: 0.7

    # Logging
    logging:
      level: "INFO"
      format: "json"
