apiVersion: apps/v1
kind: Deployment
metadata:
  name: gdpr-anonymizer
  labels:
    app: gdpr-anonymizer
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gdpr-anonymizer
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: gdpr-anonymizer
        version: v1
    spec:
      containers:
      - name: gdpr-anonymizer
        image: gdpr-anonymizer:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP

        env:
        - name: PORT
          value: "8000"
        - name: PYTHONUNBUFFERED
          value: "1"
        # LLM Provider API Keys from Secret
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: gdpr-anonymizer-secrets
              key: anthropic-api-key
              optional: true
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: gdpr-anonymizer-secrets
              key: openai-api-key
              optional: true

        # Mount config from ConfigMap
        volumeMounts:
        - name: config
          mountPath: /app/config
          readOnly: true

        # Resource limits
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi

        # Liveness probe - is the service running?
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

        # Readiness probe - is the service ready to accept traffic?
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3

        # Graceful shutdown
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 5"]

      volumes:
      - name: config
        configMap:
          name: gdpr-anonymizer-config

      # Security context
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
