apiVersion: v1
kind: Secret
metadata:
  name: gdpr-anonymizer-secrets
  labels:
    app: gdpr-anonymizer
type: Opaque
stringData:
  # IMPORTANT: Replace with actual values or use external secret management
  # DO NOT commit actual secrets to Git
  anthropic-api-key: "REPLACE_WITH_ACTUAL_KEY"
  openai-api-key: "REPLACE_WITH_ACTUAL_KEY"
