apiVersion: v1
kind: Service
metadata:
  name: gdpr-anonymizer
  labels:
    app: gdpr-anonymizer
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: gdpr-anonymizer
